FROM node:14

# Create app directory
WORKDIR /www

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY www/package*.json /www

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY /src /src
COPY /pkg /pkg
COPY /www /www

EXPOSE 8080
CMD [ "npm", "run","start" ]